name: TOP CHALLENGES CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # Tester sur deux versions de Node.js pour assurer la compatibilitu00e9
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run backend tests
      run: npm run test:backend
    
    - name: Upload backend test coverage
      uses: actions/upload-artifact@v3
      with:
        name: backend-coverage
        path: coverage/backend
  
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: backend-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 \
                                libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 \
                                libasound2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 \
                                libgtk-3-0 libgbm1
    
    - name: Run integration tests
      run: npx jest --config ./config/jest.integration.config.js
    
    - name: Upload integration test coverage
      uses: actions/upload-artifact@v3
      with:
        name: integration-coverage
        path: coverage/integration
  
  frontend-tests:
    name: Frontend Tests
    runs-on: macos-latest # MacOS runner pour Detox
    needs: integration-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install detox-cli
      run: npm install -g detox-cli
    
    - name: Install applesimutils
      run: |
        brew tap wix/brew
        brew install applesimutils
    
    - name: Cache Detox builds
      uses: actions/cache@v3
      with:
        path: ios/build
        key: ${{ runner.os }}-detox-build-${{ hashFiles('ios/**/*.pbxproj') }}
        restore-keys: ${{ runner.os }}-detox-build-
    
    - name: Run detox build
      run: detox build --configuration ios.sim.debug
    
    - name: Run frontend tests
      run: detox test --configuration ios.sim.debug --cleanup
  
  merge-coverage:
    name: Merge Test Coverage
    runs-on: ubuntu-latest
    needs: [backend-tests, integration-tests, frontend-tests]
    if: always()
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Download backend coverage
      uses: actions/download-artifact@v3
      with:
        name: backend-coverage
        path: coverage/backend
    
    - name: Download integration coverage
      uses: actions/download-artifact@v3
      with:
        name: integration-coverage
        path: coverage/integration
    
    - name: Install nyc
      run: npm install -g nyc
    
    - name: Merge coverage reports
      run: |
        nyc merge coverage/ .nyc_output/out.json
        nyc report --reporter=text --reporter=lcov
    
    - name: Upload combined coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
        verbose: true
    
    - name: Generate HTML coverage report
      run: nyc report --reporter=html
    
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
